name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: echo "mongoURI=${{ secrets.MONGO_URI }}" > .env

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ec2-52-56-219-114.eu-west-2.compute.amazonaws.com
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './*'
          target: '/home/ubuntu/my-app/'

      - name: Install PM2 and start app on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-52-56-219-114.eu-west-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo npm install pm2 -g
            cd /home/ubuntu/my-app/
            pm2 start index.js --name my-app
